name: admin_web
description: Admin Web Portal
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  dio: ^5.4.0
  dio_web_adapter: ^2.1.1
  shared_ui:
    path: ../shared/shared_ui
  shared_auth:
    path: ../shared/shared_auth
  shared_network:
    path: ../shared/shared_network
  shared_api:
    path: ../shared/shared_api
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

