name: shared_api
description: OpenAPI-generated client and API factory
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  shared_network:
    path: ../shared_network
  shared_auth:
    path: ../shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

